### ISSUE TITLE
some sql with `declare` does not generate any references (although it should)

### ISSUE THREAD

**Issue by lukas-at-harren** [Matts966/alphasql#80]
Given a query 'child_table.sql`:

```sql
declare foo_var int64;

create or replace table dataset.child_table as
select * from dataset.parent_table
```

Running `alphadag` against it, produces unexpected results, not recognising `dataset.parent_table` as the precursor to `dataset.child_table`.

```console
$ alphadag --with_tables child_table.sql
Reading paths passed as a command line arguments...
Only files that end with .sql or .bq are analyzed.
Reading "foo.sql"
digraph G {
0 [label="child_table.sql", shape="", type=query];
1 [label="dataset.child_table", shape=box, type=table];
0->1 ;
}
EXTERNAL REQUIRED TABLES:
```

Expected results:

```
digraph G {
0 [label="child_table.sql", shape="", type=query];
1 [label="dataset.child_table", shape=box, type=table];
2 [label="dataset.parent_table", shape=box, type=table];
0->1 ;
2->1 ;
}
EXTERNAL REQUIRED TABLES:
dataset.parent_table
```

I expected for `dataset.parent_table` to be the precursor to the table created in `child_table.sql`.

**Comment by Matts966** [comment]
Thank you for your contribution :)

This is caused by the line below ignoring error status

https://github.com/Matts966/alphasql/blob/8e382f8fc6452336a99abaae4dc61b2390ba0384/alphasql/identifier_resolver.cc#L82

`declare` is not supported now and should be supported in https://github.com/Matts966/alphasql/pull/78.
